[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
fee_manager = "2rxx7u9C5D5bMdjYmUz6LGkkfe6uwd2RPmgTVuidDW3B"
govern_dapp = "4iYameyivGuoQjBWAzY5fvQiDLVxmfW2vVxGaw1mMNna"
theia = "7AQNimfj3jURLjQzphNHySCBceLaFyAqtF2QcngKS17y"
theia_router_config = "Gh327SmhfBRnfaYJwwC59h8vZs3psnAZWqQm1wXPuERq"
theia_uuid_keeper = "6zEAEfszDLaJ463PVDz8raSYgGQR74gv4TTJh4BLJM4C"

[programs.localnet]
c3caller_solana = "HhXT6ksusxp1xswkvxdBHeBya4CihrKUzyav8FK863Vs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/davidkathoh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

